build:
  - .github/**/*

configuration:
  - gradlePlugin/blueprint-configuration/**/*
  - gradlePlugin/blueprint-tools/**/*

dependencies:
  - gradlePlugin/blueprint-dependency/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CONTRIBUTION.adoc

# App
app-android:
  - app-android/**/*
app-ios:
  - app-ios/**/*
app-desktop:
  - app-desktop/**/*
app-web:
  - app-web/**/*

# Feature
feature:
  - feature/**/*

# Common
common:
  - common/**/*

# Library
library:
  - library/**/*
